export const data = [
    {
        link:"https://weather-aktwtl9lh-poyrazavsever.vercel.app/",
        github:"https://github.com/poyrazavsever/form_components",
        header:"Form Components",
        language:"React",
        exp:"Login, Register, Contact Page with React & Tailwind.",
        date:"19/05/2023",   
    },
     {
        link:"https://weather-aktwtl9lh-poyrazavsever.vercel.app/",
        github:"https://github.com/poyrazavsever/Weather-App",
        header:"Weather App",
        language:"React",
        exp:"An application that shows the weather forecast in Turkey",
        date:"19/04/2023",   
    },
    {
        link:"https://tailwind-portfolio-phi.vercel.app/",
        github:"https://github.com/poyrazavsever/Basic-Portfolio",
        header:"Basic Portfolio",
        language:"React",
        exp:"Basic Portolio",
        date:"18/03/2023",   
    },
    {
        link:"https://react-firebase-instagram-web-clone-21u9.vercel.app/",
        github:"https://github.com/poyrazavsever/Instagram-Web-Clone",
        header:"Instagram Web Clone",
        language:"React",
        exp:"Instagram website clone. I did it to develop in the Firebase field.",
        date:"24/02/2023",   
    },
    {
        link:"https://www.niafix.com",
        github:"",
        header:"Niafix Website  Design",
        language:"Figma",
        exp:"I designed the website for a group called Niafix. This website showcases the group's projects and goals.",
        date:"15/03/2023",   
    },
    {
        link:"https://react-tailwind-restaurant-web-site.vercel.app/",
        github:"https://github.com/poyrazavsever/React-Tailwind-Restaurant-WebSite",
        header:"Restaurant Website",
        language:"React",
        exp:"A website for an imaginary restaurant. It includes sections such as menu, gallery, and services.",
        date:"20/09/2022",   
    },
    {
        link:"https://company-website-ruddy.vercel.app",
        github:"https://github.com/poyrazavsever/company-website",
        header: "Company Website",
        language:"React",
        exp:"Landing page for an imaginary company. It contains pages such as purchase pages, customer reviews, team introductions, and more.",
        date:"21/04/2023",   
    },
    {
        link:"https://github.com/poyrazavsever/Python-Login_Registration",
        github:"",
        header:"Login & Registration System",
        language:"Python",
        exp:"Login and registration system. One of the things I have tried to gain new skills for myself.",
        date:"11/08/2022",   
    },
    {
        link:"https://e-commerce-website-five-phi.vercel.app/",
        github:"https://github.com/poyrazavsever/E-commerce_Website",
        header:"Boutique Clothing Website",
        language:"React",
        exp:"I designed an e-commerce website for an imaginary boutique clothing store.",
        date:"2/01/2023",   
    },

    {
        link:"https://github.com/poyrazavsever/Python-Flask-Blog_Project",
        github:"https://github.com/poyrazavsever/Python-Flask-Blog_Project",
        header:"Blog Website",
        language:"Python",
        exp:"Blog Website with Flask. However, it turned out a bit amateurish.",
        date:"27/02/2022",   
    },
]
