export const data = [
    {
        link: "https://github.com/poyrazavsever/Technology-ecommerce",
        github: "",
        header: "Technology-Ecommerce",
        language: "Express.js",
        exp: "The project I created while learning Nodejs and Expressjs",
        date: "09/08/2024",
    },
    {
        link: "https://event-calendar-two-tau.vercel.app/",
        github: "https://github.com/poyrazavsever/event-calendar",
        header: "Event Calendar",
        language: "Next.js",
        exp: "Event Calendar uygulaması, kullanıcıların etkinliklerini yönetmelerini sağlayan modern bir takvim uygulamasıdır. React, Next.js ve Tailwind CSS kullanılarak geliştirilmiştir.",
        date: "08/29/2024",
    },
    {
        link: "https://absurd-project-9aq4.vercel.app/",
        github: "https://github.com/poyrazavsever/Riddle-This",
        header: "Riddle This",
        language: "TypeScript",
        exp: "I don't know why I did this. But I sure do think it looks great!",
        date: "08/29/2024",
    },
    {
        link: "https://readme-maker-rho.vercel.app/",
        github: "https://github.com/poyrazavsever/readme-maker",
        header: "Readme Maker",
        language: "Next.js",
        exp: "Welcome to the GitHub README Maker! This application allows you to generate professional and customizable README files for your GitHub projects.",
        date: "08/12/2024",
    },
    {
        link: "https://clothing-store-green.vercel.app/",
        github: "https://github.com/poyrazavsever/Clothing-Store",
        header: "Clothing Store",
        language: "Next.js",
        exp: "This project is focused on creating a visually appealing and modern web interface for the Luxe Threads brand. It is currently a front-end-only project, with plans to implement backend functionality in the future.",
        date: "08/24/2024",
    },
    {
        link: "http://www.turkish.developers.tr",
        github: "https://github.com/poyrazavsever/developers.tr-landing",
        header: "Turkish.developers.tr",
        language: "Next.js",
        exp: "Welcome to the official landing page repository for the **Turkish Developer Community**! This page is the entry point for our vibrant and ever-growing community of developers and designers. Here, you'll find everything you need to know about our mission, vision, and upcoming events.",
        date: "09/14/2024",
    },
    {
        link: "https://weather-aktwtl9lh-poyrazavsever.vercel.app/",
        github: "https://github.com/poyrazavsever/form_components",
        header: "Form Components",
        language: "React",
        exp: "Login, Register, Contact Page with React & Tailwind.",
        date: "19/05/2023",
    },
    {
        link: "https://redux-projects-5jxw.vercel.app/",
        github: "https://github.com/poyrazavsever/Redux-Projects/tree/Blog-Project?tab=readme-ov-file",
        header: "Redux-Projects",
        language: "Next.js",
        exp: "A repository showcasing projects developed while learning Redux and Redux Toolkit. Each project is organized under a separate branch.",
        date: "08/30/2024",
    },
    {
        link: "https://weather-aktwtl9lh-poyrazavsever.vercel.app/",
        github: "https://github.com/poyrazavsever/Weather-App",
        header: "Weather App",
        language: "React",
        exp: "An application that shows the weather forecast in Turkey",
        date: "19/04/2023",
    },
    {
        link: "https://tailwind-portfolio-phi.vercel.app/",
        github: "https://github.com/poyrazavsever/Basic-Portfolio",
        header: "Basic Portfolio",
        language: "React",
        exp: "Basic Portolio",
        date: "18/03/2023",
    },
    {
        link: "https://react-firebase-instagram-web-clone-21u9.vercel.app/",
        github: "https://github.com/poyrazavsever/Instagram-Web-Clone",
        header: "Instagram Web Clone",
        language: "React",
        exp: "Instagram website clone. I did it to develop in the Firebase field.",
        date: "24/02/2023",
    },
    {
        link: "https://www.figma.com/design/w7mBbH56gmg2R25YJMVZKl/Niafix?node-id=0-1&t=qi33LpNaQNoevNIr-1",
        github: "",
        header: "Niafix Website  Design",
        language: "Figma",
        exp: "I designed the website for a group called Niafix. This website showcases the group's projects and goals.",
        date: "15/03/2023",
    },
    {
        link: "https://react-tailwind-restaurant-web-site.vercel.app/",
        github: "https://github.com/poyrazavsever/React-Tailwind-Restaurant-WebSite",
        header: "Restaurant Website",
        language: "React",
        exp: "A website for an imaginary restaurant. It includes sections such as menu, gallery, and services.",
        date: "20/09/2022",
    },
    {
        link: "https://company-website-ruddy.vercel.app",
        github: "https://github.com/poyrazavsever/company-website",
        header: "Company Website",
        language: "React",
        exp: "Landing page for an imaginary company. It contains pages such as purchase pages, customer reviews, team introductions, and more.",
        date: "21/04/2023",
    },
    {
        link: "https://github.com/poyrazavsever/Python-Login_Registration",
        github: "",
        header: "Login & Registration System",
        language: "Python",
        exp: "Login and registration system. One of the things I have tried to gain new skills for myself.",
        date: "11/08/2022",
    },
    {
        link: "https://e-commerce-website-five-phi.vercel.app/",
        github: "https://github.com/poyrazavsever/E-commerce_Website",
        header: "Boutique Clothing Website",
        language: "React",
        exp: "I designed an e-commerce website for an imaginary boutique clothing store.",
        date: "2/01/2023",
    },

    {
        link: "https://github.com/poyrazavsever/Python-Flask-Blog_Project",
        github: "https://github.com/poyrazavsever/Python-Flask-Blog_Project",
        header: "Blog Website",
        language: "Python",
        exp: "Blog Website with Flask. However, it turned out a bit amateurish.",
        date: "27/02/2022",
    },
]
