export const data = [
    {
        link:"https://www.w3schools.com/html/",
        skillName: "Html",
        iconName:"AiFillHtml5",
        iconType:"ai",
        iconColor:"text-amber-600",
    },
    {
        link:"https://www.w3schools.com/css/",
        skillName: "Css",
        iconName:"SiCss3",
        iconType:"si",
        iconColor:"text-sky-400",
    },
    {
        link:"https://sass-lang.com/",
        skillName: "Scss",
        iconName:"IoLogoSass",
        iconType:"ionic5",
        iconColor:"text-pink-400",
    },
    {
        link:"https://www.javascript.com",
        skillName: "Javascript",
        iconName:"SiJavascript",
        iconType:"si",
        iconColor:"text-amber-400",
    },
    {
        link:"https://www.react.dev",
        skillName: "React",
        iconName:"IoLogoReact",
        iconType:"ionic5",
        iconColor:"text-sky-500",
    },
    {
        link:"https://www.tailwindcss.com",
        skillName: "Tailwind",
        iconName:"SiTailwindcss",
        iconType:"si",
        iconColor:"text-blue-400",
    },
    {
        link:"https://getbootstrap.com/",
        skillName: "Bootstrap",
        iconName:"SiBootstrap",
        iconType:"si",
        iconColor:"text-violet-500",
    },
    {
        link:"https://mui.com/",
        skillName: "Material UI",
        iconName:"SiMui",
        iconType:"si",
        iconColor:"text-sky-400",
    },
    {
        link:"https://nextjs.org/",
        skillName: "Nextjs",
        iconName:"SiNextdotjs",
        iconType:"si",
        iconColor:"text-neutral-200",
    },
    {
        link:"https://www.python.org/",
        skillName: "Python",
        iconName:"SiPython",
        iconType:"si",
        iconColor:"text-neutral-300",
    }, 
    {
        link:"https://flask.palletsprojects.com/en/2.3.x/",
        skillName: "Flask",
        iconName:"SiFlask",
        iconType:"si",
        iconColor:"text-neutral-300",
    },
    {
        link:"https://redux.js.org/",
        skillName: "Redux",
        iconName:"SiRedux",
        iconType:"si",
        iconColor:"text-violet-500",
    },
    {
        link:"https://git-scm.com/",
        skillName: "Git",
        iconName:"SiGit",
        iconType:"si",
        iconColor:"text-amber-700",
    },
    {
        link:"https://www.github.com/poyrazavsever",
        skillName: "Github",
        iconName:"SiGithub",
        iconType:"si",
        iconColor:"text-neutral-300",
    },
    {
        link:"https://www.figma.com/",
        skillName: "Figma",
        iconName:"SiFigma",
        iconType:"si",
        iconColor:"text-neutral-300",
    },   
    {
        link:"https://www.adobe.com/products/photoshop.html",
        skillName: "Photoshop",
        iconName:"SiAdobephotoshop",
        iconType:"si",
        iconColor:"text-sky-500",
    },  
    {
        link:"https://nodejs.org/en",
        skillName: "Node.js",
        iconName:"DiNodejsSmall",
        iconType:"di",
        iconColor:"text-green-400",
    },  
    {
        link:"https://expressjs.com/",
        skillName: "Express.js",
        iconName:"SiExpress",
        iconType:"si",
        iconColor:"text-neutral-100",
    },
    {
        link:"https://pugjs.org/api/getting-started.html",
        skillName: "Pug.js",
        iconName:"SiPug",
        iconType:"si",
        iconColor:"text-stone-500",
    },
       {
        link:"https://www.mysql.com/",
        skillName: "mysql",
        iconName:"SiMysql",
        iconType:"si",
        iconColor:"text-yellow-500",
    },
]
